двусвязный список с пай-тестами
G-K-R-git/PY200-German-LinkedList pull request #2
Opened 2021-03-03 22:26 UTC by G-K-R-git

2021-03-05 18:29 UTC, EnotYoyo requested changes

2021-03-05 18:29 UTC, EnotYoyo commented on linked_list.py
> +        # if self._prev_node is not None:
не понял, почему оно закоментировано.

2021-03-05 18:29 UTC, EnotYoyo commented on linked_list.py
> +        for current_node in self._node_iter():
Вы вставляете в конец списка. Конец списка у Вас уже есть (self.tail)

2021-03-05 18:29 UTC, EnotYoyo commented on linked_list.py
> +                    new_node.prev_node = node
break

2021-03-05 18:29 UTC, EnotYoyo commented on linked_list.py
> +                    new_node.prev_node = node
А у node.next_node проставить prev_node?

2021-03-05 18:29 UTC, EnotYoyo commented on linked_list.py
> +            if self.head is not None:
А в противном случае? tail то останется старый.

2021-03-05 18:29 UTC, EnotYoyo commented on test_all.py
> +dll_ref = linked_list.DoubleLinkedList()
Для такие случаев есть механизм fixtures. Почитайте про них в документации pytest'a (очень крутой механизм для тестирования).

2021-03-06 12:18 UTC, G-K-R-git commented on linked_list.py
> +        # if self._prev_node is not None:
По тестам в эту строчку никак не попасть

2021-03-07 19:05 UTC, EnotYoyo commented on linked_list.py
> +        # if self._prev_node is not None:
эм? Это в setter'e  
```python
        if value is not None and not isinstance(value, Node):
            raise ValueError

        if value is not None:
            self._prev_node = weakref.ref(value)
        else:
            self._prev_node = value
```

2021-03-07 19:53 UTC, G-K-R-git commented on linked_list.py
> +        # if self._prev_node is not None:
а, кажется понял. Верну

2021-03-15 20:56 UTC, EnotYoyo approved these changes

2021-03-16 06:54 UTC, merged